/* tslint:disable */
/* eslint-disable */
/**
 * Sia Modulith API
 * This is the API description for the awesome brand new FAST SiA Modulith backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AuthorDTO
 */
export interface AuthorDTO {
    /**
     * 
     * @type {number}
     * @memberof AuthorDTO
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface BookDTO
 */
export interface BookDTO {
    /**
     * 
     * @type {string}
     * @memberof BookDTO
     */
    'authorName'?: string;
    /**
     * 
     * @type {number}
     * @memberof BookDTO
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof BookDTO
     */
    'title'?: string;
}
/**
 * 
 * @export
 * @interface JsonPatchItem
 */
export interface JsonPatchItem {
    /**
     * 
     * @type {JsonPatchOps}
     * @memberof JsonPatchItem
     */
    'op': JsonPatchOps;
    /**
     * 
     * @type {string}
     * @memberof JsonPatchItem
     */
    'path': string;
    /**
     * 
     * @type {JsonPatchValue}
     * @memberof JsonPatchItem
     */
    'value'?: JsonPatchValue;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const JsonPatchOps = {
    Add: 'add',
    Remove: 'remove',
    Replace: 'replace',
    Move: 'move',
    Copy: 'copy',
    Test: 'test'
} as const;

export type JsonPatchOps = typeof JsonPatchOps[keyof typeof JsonPatchOps];


/**
 * 
 * @export
 * @interface JsonPatchValue
 */
export interface JsonPatchValue {
}

/**
 * AuthorControllerApi - axios parameter creator
 * @export
 */
export const AuthorControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * <b>Allowed paths are:</b><br><br>- name -> change the name of the author<br>- books/- -> add and remove items from the books of this author<br>- books/-/title -> update an author\'s book title<br>- books/-/isbn -> update an author\'s book isbn
         * @param {number} id 
         * @param {Array<JsonPatchItem>} jsonPatchItem 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAuthor: async (id: number, jsonPatchItem: Array<JsonPatchItem>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateAuthor', 'id', id)
            // verify required parameter 'jsonPatchItem' is not null or undefined
            assertParamExists('updateAuthor', 'jsonPatchItem', jsonPatchItem)
            const localVarPath = `/api/v1/authors/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(jsonPatchItem, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthorControllerApi - functional programming interface
 * @export
 */
export const AuthorControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthorControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * <b>Allowed paths are:</b><br><br>- name -> change the name of the author<br>- books/- -> add and remove items from the books of this author<br>- books/-/title -> update an author\'s book title<br>- books/-/isbn -> update an author\'s book isbn
         * @param {number} id 
         * @param {Array<JsonPatchItem>} jsonPatchItem 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAuthor(id: number, jsonPatchItem: Array<JsonPatchItem>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAuthor(id, jsonPatchItem, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorControllerApi.updateAuthor']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthorControllerApi - factory interface
 * @export
 */
export const AuthorControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthorControllerApiFp(configuration)
    return {
        /**
         * <b>Allowed paths are:</b><br><br>- name -> change the name of the author<br>- books/- -> add and remove items from the books of this author<br>- books/-/title -> update an author\'s book title<br>- books/-/isbn -> update an author\'s book isbn
         * @param {number} id 
         * @param {Array<JsonPatchItem>} jsonPatchItem 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAuthor(id: number, jsonPatchItem: Array<JsonPatchItem>, options?: any): AxiosPromise<void> {
            return localVarFp.updateAuthor(id, jsonPatchItem, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthorControllerApi - object-oriented interface
 * @export
 * @class AuthorControllerApi
 * @extends {BaseAPI}
 */
export class AuthorControllerApi extends BaseAPI {
    /**
     * <b>Allowed paths are:</b><br><br>- name -> change the name of the author<br>- books/- -> add and remove items from the books of this author<br>- books/-/title -> update an author\'s book title<br>- books/-/isbn -> update an author\'s book isbn
     * @param {number} id 
     * @param {Array<JsonPatchItem>} jsonPatchItem 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorControllerApi
     */
    public updateAuthor(id: number, jsonPatchItem: Array<JsonPatchItem>, options?: RawAxiosRequestConfig) {
        return AuthorControllerApiFp(this.configuration).updateAuthor(id, jsonPatchItem, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * BookControllerApi - axios parameter creator
 * @export
 */
export const BookControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * <b>Allowed paths are:</b><br><br>- title<br>- author/id<br>- isbn
         * @param {number} id 
         * @param {Array<JsonPatchItem>} jsonPatchItem 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBook: async (id: number, jsonPatchItem: Array<JsonPatchItem>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateBook', 'id', id)
            // verify required parameter 'jsonPatchItem' is not null or undefined
            assertParamExists('updateBook', 'jsonPatchItem', jsonPatchItem)
            const localVarPath = `/api/v1/books/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(jsonPatchItem, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BookControllerApi - functional programming interface
 * @export
 */
export const BookControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BookControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * <b>Allowed paths are:</b><br><br>- title<br>- author/id<br>- isbn
         * @param {number} id 
         * @param {Array<JsonPatchItem>} jsonPatchItem 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBook(id: number, jsonPatchItem: Array<JsonPatchItem>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateBook(id, jsonPatchItem, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BookControllerApi.updateBook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BookControllerApi - factory interface
 * @export
 */
export const BookControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BookControllerApiFp(configuration)
    return {
        /**
         * <b>Allowed paths are:</b><br><br>- title<br>- author/id<br>- isbn
         * @param {number} id 
         * @param {Array<JsonPatchItem>} jsonPatchItem 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBook(id: number, jsonPatchItem: Array<JsonPatchItem>, options?: any): AxiosPromise<void> {
            return localVarFp.updateBook(id, jsonPatchItem, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BookControllerApi - object-oriented interface
 * @export
 * @class BookControllerApi
 * @extends {BaseAPI}
 */
export class BookControllerApi extends BaseAPI {
    /**
     * <b>Allowed paths are:</b><br><br>- title<br>- author/id<br>- isbn
     * @param {number} id 
     * @param {Array<JsonPatchItem>} jsonPatchItem 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookControllerApi
     */
    public updateBook(id: number, jsonPatchItem: Array<JsonPatchItem>, options?: RawAxiosRequestConfig) {
        return BookControllerApiFp(this.configuration).updateBook(id, jsonPatchItem, options).then((request) => request(this.axios, this.basePath));
    }
}



