/* tslint:disable */
/* eslint-disable */
/**
 * Sia Modulith API
 * This is the API description for the awesome brand new FAST SiA Modulith backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

