openapi: 3.0.1
info:
  description: This is the API description for the awesome brand new FAST SiA Modulith
    backend.
  title: Sia Modulith API
  version: "1.0"
servers:
- description: Generated server url
  url: http://localhost:8083
paths:
  /api/v1/authors/{id}:
    patch:
      description: <b>Allowed paths are:</b><br><br>- name -> change the name of the
        author<br>- books/- -> add and remove items from the books of this author<br>-
        books/-/title -> update an author's book title<br>- books/-/isbn -> update
        an author's book isbn
      operationId: updateAuthor
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/JsonPatchItem"
        required: true
      responses:
        "200":
          description: Successful operation
        "304":
          description: Not modified
        "400":
          description: Precondition failed
        "404":
          description: Resource not found
        "500":
          description: Internal server error
      tags:
      - author-controller
  /api/v1/books/{id}:
    patch:
      description: <b>Allowed paths are:</b><br><br>- title<br>- author/id<br>- isbn
      operationId: updateBook
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/JsonPatchItem"
        required: true
      responses:
        "200":
          description: Successful operation
        "304":
          description: Not modified
        "400":
          description: Precondition failed
        "404":
          description: Resource not found
        "500":
          description: Internal server error
      tags:
      - book-controller
components:
  schemas:
    AuthorDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    BookDTO:
      type: object
      properties:
        authorName:
          type: string
        id:
          type: integer
          format: int32
        title:
          type: string
    JsonNode:
      type: object
    JsonPatchItem:
      type: object
      properties:
        op:
          $ref: "#/components/schemas/JsonPatchOps"
        path:
          type: string
        value:
          $ref: "#/components/schemas/JsonPatchValue"
      required:
      - op
      - path
    JsonPatchOps:
      type: string
      enum:
      - add
      - remove
      - replace
      - move
      - copy
      - test
    JsonPatchValue:
      anyOf:
      - type: string
      - type: number
      - type: boolean
      - type: object
